# kafka config
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS: localhost:9092}

# spring freemarker
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.enabled=true
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.check-template-location=true
