# kafka config
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS: localhost:9092}

# spring freemarker
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.enabled=true
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.check-template-location=true

# meaning total file size cannot exceed 128KB.
spring.servlet.multipart.max-file-size=128KB
# meaning total request size for a multipart/form-data cannot exceed 128KB.
spring.servlet.multipart.max-request-size=128KB

# spring security configuration
spring.ldap.embedded.ldif=classpath:test-server.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389

# spring redis
# Redis数据库索引（默认为0）
spring.redis.database=0
# Redis服务器地址
spring.redis.host=${SPRING_REDIS_HOST:localhost}
# Redis服务器连接端口
spring.redis.port=6379
# Redis服务器连接密码（默认为空）
spring.redis.password=